version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - .:/var/symfony-rabbit
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - app
    networks:
      - symfony-network

  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/symfony-rabbit
    depends_on:
      - rabbitmq
      - redis
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://user:password@db:5432/app_db
    ports:
      - "8000:80"
    networks:
      - symfony-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - symfony-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # RabbitMQ
      - "15672:15672"  # Management UI
    networks:
      - symfony-network

  perf_test:
    image: pivotalrabbitmq/perf-test
    depends_on:
      - rabbitmq
    restart: "no"
    networks:
      - symfony-network

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOO_MAX_BUFFER_SIZE=5242880
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - symfony-network

  zoonavigator:
    image: elkozmon/zoonavigator:1.0.0
    container_name: zoonavigator
    environment:
      ZOOKEEPER_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks:
      - symfony-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    networks:
      - symfony-network

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - symfony-network

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    depends_on:
      - kafka
    ports:
      - "9308:9308"
    environment:
      KAFKA_SERVER: kafka:9092
    command:
      - "--kafka.server=kafka:9092"
    networks:
      - symfony-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8080:8080"
    networks:
      - symfony-network

  db:
    image: postgres:15
    container_name: symfony_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - symfony-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9001:9001"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - symfony-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - symfony-network

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - symfony-network

volumes:
  clickhouse-data:
  db_data:
  grafana-data:
  database_data:

networks:
  symfony-network:
    driver: bridge
