parameters:


imports:
    - { resource: 'packages/schema_registry.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Infrastructure\Avro\SchemaRegistryClientInterface: '@App\Infrastructure\Avro\ConfluenceSchemaRegistryClient'
    App\Infrastructure\Avro\ConfluenceSchemaRegistryClient:
        arguments:
            $schemaRegistryService: '@App\Infrastructure\Avro\SchemaRegistryService'
        public: true
        shared: true

    App\Infrastructure\Rabbitmq\RabbitmqConnectionInterface: '@App\Infrastructure\Rabbitmq\RabbitmqConnection'

    App\Infrastructure\Rabbitmq\RabbitmqConnection:
        public: true
        shared: true
        arguments:
            - '@rabbitmq.connection'

    rabbitmq.connection:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        factory: [ 'App\Infrastructure\Rabbitmq\RabbitmqConnectionFactory', 'createConnection' ]
        shared: true

    App\Infrastructure\Elastic\Core\ElasticSearchConnectionInterface: '@App\Infrastructure\Elastic\Core\ElasticSearchConnection'
